name: todo_impl
description: todo api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  data:
    path: ../../../core/data
  di:
    path: ../../../core/di
  domain:
    path: ../../../common/domain
  flutter:
    sdk: flutter
  todo_api:
    path: ../api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
